#!/bin/bash
file="/root/snmp-base.yaml"

if [ ! -f $file ]; then
    fail-message "snmp-base.yaml does not exist at /root"
fi

if [[ $(stat -c "%a" $file) != 646 ]]; then
    fail-message "Incorrect permissions for snmp-base.yaml"
fi